**Kaggle에서 Hello world로 많이 사용**

## 타이타닉 데이터셋으로 전처리 연습하기

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## 데이터 셋: 타이타닉 데이터셋 (출처: Kaggle.com)

In [6]:
df.head()

# survied : y

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

* PassengerId: 승객 아이디
* Survived: 생존 여부, 1: 생존, 0: 사망
* Pclass: 등급
* Name: 성함
* Sex: 성별
* Age: 나이
* SibSp: 형제, 자매, 배우자 수
* Parch: 부모, 자식 수
* Ticket: 티켓번호
* Fare: 요즘
* Cabin: 좌석번호
* Embarked: 탑승 항구

In [ ]:
train.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 전처리: train / validation 세트 나누기

1. 먼저, feature 와 label을 정의합니다.
2. feature / label을 정의했으면, 적절한 비율로 train / validation set을 나눕니다.

In [8]:
# 전체 데이터중 학습에 사용할 데이터를 선택하자.
feature = ['Pclass', 'Sex', 'Age', 'Fare']

In [9]:
# 예측 해야할 값
label = ['Survived']

In [11]:
df[feature].head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [12]:
df[feature].shape

(891, 4)

In [13]:
df[label].head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [23]:
# 전체 데이터수를 확인해 보자
df.info()
train = df.copy()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [24]:
from sklearn.model_selection import train_test_split

* **test_size**: validation set에 할당할 비율 (20% -> 0.2)
* **shuffle**: 셔플 옵션 (기본 True)
* **random_state**: 랜덤 시드값

전체 데이터를 train data와 validation data의 비율을 8:2로 나눈다.

In [25]:
x_train, x_valid, y_train, y_valid = train_test_split(train[feature], train[label], test_size=0.2, shuffle=True, random_state=30)

In [26]:
x_train.shape, y_train.shape

((712, 4), (712, 1))

In [27]:
x_valid.shape, y_valid.shape

((179, 4), (179, 1))

## 전처리: 결측치

In [28]:
#전체 데이터수 891개와 비교해서 갯수가 부족한 항목을 확인하자
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

결측치를 확인하는 방법은 pandas의 **isnull()**

그리고 합계를 구하는 sum()을 통해 한 눈에 확인할 수 있습니다.

In [31]:
train.isnull() # 결과값이 boolean indexing으로 나옴. 분석이 어려움

train.isnull().sum() #boolean > 결측치 값이 몇개인지 더해서 보여줌

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

개별 column의 결측치에 대하여 확인하는 방법은 다음과 같습니다.

In [32]:
train['Age'].isnull().sum()

177

[Impute 도큐먼트](https://scikit-learn.org/stable/modules/impute.html)

### 1. 수치형 (Numerical Column) 데이터에 대한 결측치 처리

In [ ]:
# 수치형 데이터는 대체로 평균 값을 구한뒤, 평균 값으로 채워준다.

In [33]:
# 0으로 채웠을때의 통계값을 출력해보자
train['Age'].fillna(0).describe()

count    891.000000
mean      23.799293
std       17.596074
min        0.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [35]:
# 평균 값으로 채웠을때의 통계값을 출력해보자
train['Age'].fillna(train['Age'].mean()).describe()

# 결측치 처리를 위해 평균값으로 채울지, 중앙값으로 채울지는
# 비교해보고 채우는것도 방법

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

#### 사이킷런의 imputer를 활용하면 2개 이상의 column을 한 번에 처리할 수 있다.

In [36]:
from sklearn.impute import SimpleImputer

In [37]:
# 입력으로 넣는 데이터의 평균치를 사용해서 Nan값을 채워주는 imputer 생성
# 입력으로 넣을수 있는 항목은 숫자
imputer = SimpleImputer(strategy='mean')

fit() 을 통해 결측치에 대한 학습을 진행합니다.

In [38]:
# fit은 학습하는데 사용하는 메소드
# fit함수를 통해서 imputer의 평균값을 계산 >> 아직 안 넣었음!
imputer.fit(train[['Age']])

SimpleImputer()

transform() 은 실제 결측치에 대한 처리를 해주는 함수합니다.

---

In [39]:
# transform에서 null값을 채워준다.
result = imputer.transform(train[['Age']])

In [40]:
result

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [18.        ],
       [ 7.        ],
       [21.        ],
       [49.        ],
       [29.        ],
       [65.        ],
       [29.69911765],
       [21.        ],
       [28.5       ],
       [ 5.        ],
       [11.        ],
       [22.        ],
       [38.        ],
       [45.        ],
       [ 4.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [19.        ],
       [17.        ],
       [26.        ],
       [32.        ],
       [16.        ],
       [21.        ],
       [26.        ],
       [32.        ],
       [25.        ],
       [29.69911765],
       [29.69911765],
       [ 0.83      ],
       [30.        ],
       [22.        ],
       [29.        ],
       [29.69911765],
       [28.        ],
       [17.        ],
       [33.        ],
       [16.        ],
       [29.69911765],
       [23.        ],
       [24.        ],
       [29.        ],
       [20.        ],
       [46.        ],
       [26.        ],
       [59.        ],
       [29.69911765],
       [71.        ],
       [23.        ],
       [34.        ],
       [34.        ],
       [28.        ],
       [29.69911765],
       [21.        ],
       [33.        ],
       [37.        ],
       [28.        ],
       [21.        ],
       [29.69911765],
       [38.        ],
       [29.69911765],
       [47.        ],
       [14.5       ],
       [22.        ],
       [20.        ],
       [17.        ],
       [21.        ],
       [70.5       ],
       [29.        ],
       [24.        ],
       [ 2.        ],
       [21.        ],
       [29.69911765],
       [32.5       ],
       [32.5       ],
       [54.        ],
       [12.        ],
       [29.69911765],
       [24.        ],
       [29.69911765],
       [45.        ],
       [33.        ],
       [20.        ],
       [47.        ],
       [29.        ],
       [25.        ],
       [23.        ],
       [19.        ],
       [37.        ],
       [16.        ],
       [24.        ],
       [29.69911765],
       [22.        ],
       [24.        ],
       [19.        ],
       [18.        ],
       [19.        ],
       [27.        ],
       [ 9.        ],
       [36.5       ],
       [42.        ],
       [51.        ],
       [22.        ],
       [55.5       ],
       [40.5       ],
       [29.69911765],
       [51.        ],
       [16.        ],
       [30.        ],
       [29.69911765],
       [29.69911765],
       [44.        ],
       [40.        ],
       [26.        ],
       [17.        ],
       [ 1.        ],
       [ 9.        ],
       [29.69911765],
       [45.        ],
       [29.69911765],
       [28.        ],
       [61.        ],
       [ 4.        ],
       [ 1.        ],
       [21.        ],
       [56.        ],
       [18.        ],
       [29.69911765],
       [50.        ],
       [30.        ],
       [36.        ],
       [29.69911765],
       [29.69911765],
       [ 9.        ],
       [ 1.        ],
       [ 4.        ],
       [29.69911765],
       [29.69911765],
       [45.        ],
       [40.        ],
       [36.        ],
       [32.        ],
       [19.        ],
       [19.        ],
       [ 3.        ],
       [44.        ],
       [58.        ],
       [29.69911765],
       [42.        ],
       [29.69911765],
       [24.        ],
       [28.        ],
       [29.69911765],
       [34.        ],
       [45.5       ],
       [18.        ],
       [ 2.        ],
       [32.        ],
       [26.        ],
       [16.        ],
       [40.        ],
       [24.        ],
       [35.        ],
       [22.        ],
       [30.        ],
       [29.69911765],
       [31.        ],
       [27.        ],
       [42.        ],
       [32.        ],
       [30.        ],
       [16.        ],
       [27.        ],
       [51.        ],
       [29.69911765],
       [38.        ],
       [22.        ],
       [19.        ],
       [20.5       ],
       [18.        ],
       [29.69911765],
       [35.        ],
       [29.        ],
       [59.        ],
       [ 5.        ],
       [24.        ],
       [29.69911765],
       [44.        ],
       [ 8.        ],
       [19.        ],
       [33.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [22.        ],
       [30.        ],
       [44.        ],
       [25.        ],
       [24.        ],
       [37.        ],
       [54.        ],
       [29.69911765],
       [29.        ],
       [62.        ],
       [30.        ],
       [41.        ],
       [29.        ],
       [29.69911765],
       [30.        ],
       [35.        ],
       [50.        ],
       [29.69911765],
       [ 3.        ],
       [52.        ],
       [40.        ],
       [29.69911765],
       [36.        ],
       [16.        ],
       [25.        ],
       [58.        ],
       [35.        ],
       [29.69911765],
       [25.        ],
       [41.        ],
       [37.        ],
       [29.69911765],
       [63.        ],
       [45.        ],
       [29.69911765],
       [ 7.        ],
       [35.        ],
       [65.        ],
       [28.        ],
       [16.        ],
       [19.        ],
       [29.69911765],
       [33.        ],
       [30.        ],
       [22.        ],
       [42.        ],
       [22.        ],
       [26.        ],
       [19.        ],
       [36.        ],
       [24.        ],
       [24.        ],
       [29.69911765],
       [23.5       ],
       [ 2.        ],
       [29.69911765],
       [50.        ],
       [29.69911765],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [ 0.92      ],
       [29.69911765],
       [17.        ],
       [30.        ],
       [30.        ],
       [24.        ],
       [18.        ],
       [26.        ],
       [28.        ],
       [43.        ],
       [26.        ],
       [24.        ],
       [54.        ],
       [31.        ],
       [40.        ],
       [22.        ],
       [27.        ],
       [30.        ],
       [22.        ],
       [29.69911765],
       [36.        ],
       [61.        ],
       [36.        ],
       [31.        ],
       [16.        ],
       [29.69911765],
       [45.5       ],
       [38.        ],
       [16.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [41.        ],
       [45.        ],
       [45.        ],
       [ 2.        ],
       [24.        ],
       [28.        ],
       [25.        ],
       [36.        ],
       [24.        ],
       [40.        ],
       [29.69911765],
       [ 3.        ],
       [42.        ],
       [23.        ],
       [29.69911765],
       [15.        ],
       [25.        ],
       [29.69911765],
       [28.        ],
       [22.        ],
       [38.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.        ],
       [45.        ],
       [35.        ],
       [29.69911765],
       [30.        ],
       [60.        ],
       [29.69911765],
       [29.69911765],
       [24.        ],
       [25.        ],
       [18.        ],
       [19.        ],
       [22.        ],
       [ 3.        ],
       [29.69911765],
       [22.        ],
       [27.        ],
       [20.        ],
       [19.        ],
       [42.        ],
       [ 1.        ],
       [32.        ],
       [35.        ],
       [29.69911765],
       [18.        ],
       [ 1.        ],
       [36.        ],
       [29.69911765],
       [17.        ],
       [36.        ],
       [21.        ],
       [28.        ],
       [23.        ],
       [24.        ],
       [22.        ],
       [31.        ],
       [46.        ],
       [23.        ],
       [28.        ],
       [39.        ],
       [26.        ],
       [21.        ],
       [28.        ],
       [20.        ],
       [34.        ],
       [51.        ],
       [ 3.        ],
       [21.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [33.        ],
       [29.69911765],
       [44.        ],
       [29.69911765],
       [34.        ],
       [18.        ],
       [30.        ],
       [10.        ],
       [29.69911765],
       [21.        ],
       [29.        ],
       [28.        ],
       [18.        ],
       [29.69911765],
       [28.        ],
       [19.        ],
       [29.69911765],
       [32.        ],
       [28.        ],
       [29.69911765],
       [42.        ],
       [17.        ],
       [50.        ],
       [14.        ],
       [21.        ],
       [24.        ],
       [64.        ],
       [31.        ],
       [45.        ],
       [20.        ],
       [25.        ],
       [28.        ],
       [29.69911765],
       [ 4.        ],
       [13.        ],
       [34.        ],
       [ 5.        ],
       [52.        ],
       [36.        ],
       [29.69911765],
       [30.        ],
       [49.        ],
       [29.69911765],
       [29.        ],
       [65.        ],
       [29.69911765],
       [50.        ],
       [29.69911765],
       [48.        ],
       [34.        ],
       [47.        ],
       [48.        ],
       [29.69911765],
       [38.        ],
       [29.69911765],
       [56.        ],
       [29.69911765],
       [ 0.75      ],
       [29.69911765],
       [38.        ],
       [33.        ],
       [23.        ],
       [22.        ],
       [29.69911765],
       [34.        ],
       [29.        ],
       [22.        ],
       [ 2.        ],
       [ 9.        ],
       [29.69911765],
       [50.        ],
       [63.        ],
       [25.        ],
       [29.69911765],
       [35.        ],
       [58.        ],
       [30.        ],
       [ 9.        ],
       [29.69911765],
       [21.        ],
       [55.        ],
       [71.        ],
       [21.        ],
       [29.69911765],
       [54.        ],
       [29.69911765],
       [25.        ],
       [24.        ],
       [17.        ],
       [21.        ],
       [29.69911765],
       [37.        ],
       [16.        ],
       [18.        ],
       [33.        ],
       [29.69911765],
       [28.        ],
       [26.        ],
       [29.        ],
       [29.69911765],
       [36.        ],
       [54.        ],
       [24.        ],
       [47.        ],
       [34.        ],
       [29.69911765],
       [36.        ],
       [32.        ],
       [30.        ],
       [22.        ],
       [29.69911765],
       [44.        ],
       [29.69911765],
       [40.5       ],
       [50.        ],
       [29.69911765],
       [39.        ],
       [23.        ],
       [ 2.        ],
       [29.69911765],
       [17.        ],
       [29.69911765],
       [30.        ],
       [ 7.        ],
       [45.        ],
       [30.        ],
       [29.69911765],
       [22.        ],
       [36.        ],
       [ 9.        ],
       [11.        ],
       [32.        ],
       [50.        ],
       [64.        ],
       [19.        ],
       [29.69911765],
       [33.        ],
       [ 8.        ],
       [17.        ],
       [27.        ],
       [29.69911765],
       [22.        ],
       [22.        ],
       [62.        ],
       [48.        ],
       [29.69911765],
       [39.        ],
       [36.        ],
       [29.69911765],
       [40.        ],
       [28.        ],
       [29.69911765],
       [29.69911765],
       [24.        ],
       [19.        ],
       [29.        ],
       [29.69911765],
       [32.        ],
       [62.        ],
       [53.        ],
       [36.        ],
       [29.69911765],
       [16.        ],
       [19.        ],
       [34.        ],
       [39.        ],
       [29.69911765],
       [32.        ],
       [25.        ],
       [39.        ],
       [54.        ],
       [36.        ],
       [29.69911765],
       [18.        ],
       [47.        ],
       [60.        ],
       [22.        ],
       [29.69911765],
       [35.        ],
       [52.        ],
       [47.        ],
       [29.69911765],
       [37.        ],
       [36.        ],
       [29.69911765],
       [49.        ],
       [29.69911765],
       [49.        ],
       [24.        ],
       [29.69911765],
       [29.69911765],
       [44.        ],
       [35.        ],
       [36.        ],
       [30.        ],
       [27.        ],
       [22.        ],
       [40.        ],
       [39.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [35.        ],
       [24.        ],
       [34.        ],
       [26.        ],
       [ 4.        ],
       [26.        ],
       [27.        ],
       [42.        ],
       [20.        ],
       [21.        ],
       [21.        ],
       [61.        ],
       [57.        ],
       [21.        ],
       [26.        ],
       [29.69911765],
       [80.        ],
       [51.        ],
       [32.        ],
       [29.69911765],
       [ 9.        ],
       [28.        ],
       [32.        ],
       [31.        ],
       [41.        ],
       [29.69911765],
       [20.        ],
       [24.        ],
       [ 2.        ],
       [29.69911765],
       [ 0.75      ],
       [48.        ],
       [19.        ],
       [56.        ],
       [29.69911765],
       [23.        ],
       [29.69911765],
       [18.        ],
       [21.        ],
       [29.69911765],
       [18.        ],
       [24.        ],
       [29.69911765],
       [32.        ],
       [23.        ],
       [58.        ],
       [50.        ],
       [40.        ],
       [47.        ],
       [36.        ],
       [20.        ],
       [32.        ],
       [25.        ],
       [29.69911765],
       [43.        ],
       [29.69911765],
       [40.        ],
       [31.        ],
       [70.        ],
       [31.        ],
       [29.69911765],
       [18.        ],
       [24.5       ],
       [18.        ],
       [43.        ],
       [36.        ],
       [29.69911765],
       [27.        ],
       [20.        ],
       [14.        ],
       [60.        ],
       [25.        ],
       [14.        ],
       [19.        ],
       [18.        ],
       [15.        ],
       [31.        ],
       [ 4.        ],
       [29.69911765],
       [25.        ],
       [60.        ],
       [52.        ],
       [44.        ],
       [29.69911765],
       [49.        ],
       [42.        ],
       [18.        ],
       [35.        ],
       [18.        ],
       [25.        ],
       [26.        ],
       [39.        ],
       [45.        ],
       [42.        ],
       [22.        ],
       [29.69911765],
       [24.        ],
       [29.69911765],
       [48.        ],
       [29.        ],
       [52.        ],
       [19.        ],
       [38.        ],
       [27.        ],
       [29.69911765],
       [33.        ],
       [ 6.        ],
       [17.        ],
       [34.        ],
       [50.        ],
       [27.        ],
       [20.        ],
       [30.        ],
       [29.69911765],
       [25.        ],
       [25.        ],
       [29.        ],
       [11.        ],
       [29.69911765],
       [23.        ],
       [23.        ],
       [28.5       ],
       [48.        ],
       [35.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [36.        ],
       [21.        ],
       [24.        ],
       [31.        ],
       [70.        ],
       [16.        ],
       [30.        ],
       [19.        ],
       [31.        ],
       [ 4.        ],
       [ 6.        ],
       [33.        ],
       [23.        ],
       [48.        ],
       [ 0.67      ],
       [28.        ],
       [18.        ],
       [34.        ],
       [33.        ],
       [29.69911765],
       [41.        ],
       [20.        ],
       [36.        ],
       [16.        ],
       [51.        ],
       [29.69911765],
       [30.5       ],
       [29.69911765],
       [32.        ],
       [24.        ],
       [48.        ],
       [57.        ],
       [29.69911765],
       [54.        ],
       [18.        ],
       [29.69911765],
       [ 5.        ],
       [29.69911765],
       [43.        ],
       [13.        ],
       [17.        ],
       [29.        ],
       [29.69911765],
       [25.        ],
       [25.        ],
       [18.        ],
       [ 8.        ],
       [ 1.        ],
       [46.        ],
       [29.69911765],
       [16.        ],
       [29.69911765],
       [29.69911765],
       [25.        ],
       [39.        ],
       [49.        ],
       [31.        ],
       [30.        ],
       [30.        ],
       [34.        ],
       [31.        ],
       [11.        ],
       [ 0.42      ],
       [27.        ],
       [31.        ],
       [39.        ],
       [18.        ],
       [39.        ],
       [33.        ],
       [26.        ],
       [39.        ],
       [35.        ],
       [ 6.        ],
       [30.5       ],
       [29.69911765],
       [23.        ],
       [31.        ],
       [43.        ],
       [10.        ],
       [52.        ],
       [27.        ],
       [38.        ],
       [27.        ],
       [ 2.        ],
       [29.69911765],
       [29.69911765],
       [ 1.        ],
       [29.69911765],
       [62.        ],
       [15.        ],
       [ 0.83      ],
       [29.69911765],
       [23.        ],
       [18.        ],
       [39.        ],
       [21.        ],
       [29.69911765],
       [32.        ],
       [29.69911765],
       [20.        ],
       [16.        ],
       [30.        ],
       [34.5       ],
       [17.        ],
       [42.        ],
       [29.69911765],
       [35.        ],
       [28.        ],
       [29.69911765],
       [ 4.        ],
       [74.        ],
       [ 9.        ],
       [16.        ],
       [44.        ],
       [18.        ],
       [45.        ],
       [51.        ],
       [24.        ],
       [29.69911765],
       [41.        ],
       [21.        ],
       [48.        ],
       [29.69911765],
       [24.        ],
       [42.        ],
       [27.        ],
       [31.        ],
       [29.69911765],
       [ 4.        ],
       [26.        ],
       [47.        ],
       [33.        ],
       [47.        ],
       [28.        ],
       [15.        ],
       [20.        ],
       [19.        ],
       [29.69911765],
       [56.        ],
       [25.        ],
       [33.        ],
       [22.        ],
       [28.        ],
       [25.        ],
       [39.        ],
       [27.        ],
       [19.        ],
       [29.69911765],
       [26.        ],
       [32.        ]])

In [41]:
#결과값은 numpy.ndarray로 저장된다.
type(result)

numpy.ndarray

In [42]:
train[['Age']] = result

In [43]:
# Age의 Nan이 하나도 없다.
train[['Age']].isnull().sum()

Age    0
dtype: int64

In [44]:
train[['Age']].describe()

              Age
count  891.000000
mean    29.699118
std     13.002015
min      0.420000
25%     22.000000
50%     29.699118
75%     35.000000
max     80.000000

#### fit_transform()은 fit()과 transform()을 한 번에 해주는 함수 입니다.

In [45]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [46]:
train[['Age']].isnull().sum()

Age    177
dtype: int64

In [47]:
# 중앙값(median)은 n개의 값을 크기 순으로 늘어놓았을 때 가장 가운데에 있는 숫자이다
# 예) 1,1,2,3,4,5,5,5,5,7,8,9,10,11,24의 경우 평균값은 100/25 = 6.666이지만
#     중앙값은 5이다
#imputer = SimpleImputer(strategy='mean')
imputer = SimpleImputer(strategy='median')

In [48]:
#result = imputer.fit_transform(train[['Age']])
train[['Age']] = imputer.fit_transform(train[['Age']])

In [49]:
#train[['Age']] = result

In [50]:
train[['Age']].isnull().sum()

Age    0
dtype: int64

### 2.  (Categorical Column) 데이터에 대한 결측치 처리
문자형 데이터의 결측치를 채워줄 경우는 가장 빈도수가 높은 것으로 채워준다.

In [52]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

1개의 column을 처리하는 경우

In [53]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [54]:
train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [55]:
train['Embarked'].mode()

# mode() : 최빈값. 최다 빈도수가 많은 값

0    S
Name: Embarked, dtype: object

In [ ]:
# Embarked 결측치 > 최빈값 S로 채워주기

train['Embarked'].fillna('S')

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

Imputer를 사용하는 경우 : 2개 이상의 column을 처리할 때

In [ ]:
# sklearn의 simpleImputer를 사용해서 'Embarked'의 결측치를 최빈값으로 채우자
imputer = SimpleImputer(strategy='most_frequent')

In [ ]:
train[['Embarked']] = imputer.fit_transform(train[['Embarked']])

In [ ]:
train[['Embarked']].isnull().sum()

Embarked    0
dtype: int64

## Label Encoding : 문자(categorical)를 수치(numerical)로 변환

학습을 위해서 모든 문자로된 **데이터는 수치로 변환**하여야 합니다.

In [56]:
train.info()

# 문자열 데이터 중, 수치로 분석할 데이터는 숫자형으로 변환한다

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [57]:
# 방법 1>
# 아래와 같이 함수를 만들어서 문자열을 수치로 변환할 수 있다
def convert(data):
    if data == 'male':
        return 1
    elif data == 'female':
        return 0

In [58]:
train['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [59]:
train['Sex'].apply(convert)

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [ ]:
# 방법 2>
# 사이킷런에서 LabelEncoder라는 함수를 사용할 수도 있다.

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
le = LabelEncoder()

In [62]:
# 새로운 컬럼을 생성
train['Sex_num'] = le.fit_transform(train['Sex'])

In [63]:
# 자동으로 만들어주는거라, 뭐가 뭔지 잘 모름 ㅎ

train['Sex_num'].value_counts()

Sex_num
1    577
0    314
Name: count, dtype: int64

In [64]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Sex_num      891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [65]:
# 어떤게 1인지, 어떤게 0인지 Label달아준건지 확인하려면

le.classes_

array(['female', 'male'], dtype=object)

In [66]:
# 테스트
le.inverse_transform([0, 1, 1, 0, 0, 1, 1])

array(['female', 'male', 'male', 'female', 'female', 'male', 'male'],
      dtype=object)

NaN 값이 포함되어 있다면, `LabelEncoder`가 정상 동작하지 않습니다.

In [69]:
le.fit_transform(train['Embarked'])

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 3, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 2, 0,
       1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 0, 2, 2, 2, 1, 1, 2, 0, 0, 2, 1, 2, 0, 0, 1, 0, 0, 2, 2, 0,
       2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 0,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2,
       0, 2, 1, 0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 1, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 1,
       2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 1, 2,
       2, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 3, 0, 2, 0, 2, 2, 0,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1])

In [70]:
le.classes_

array(['C', 'Q', 'S', nan], dtype=object)

In [71]:
train['Embarked'] = train['Embarked'].fillna('S')

In [72]:
train['Embarked'] = le.fit_transform(train['Embarked'])

In [73]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    int64
 12  Sex_num      891 non-null    int64
dtypes: float64(2), int64(7), object(4)
memory usage: 90.6+ KB

## 원 핫 인코딩 (One Hot Encoding)

In [74]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [75]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

`Embarked`를 살펴봅시다

In [76]:
# 'Embarked' column안에서 문자열의 클래스 갯수를 확인
train['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [77]:
train['Embarked'] = train['Embarked'].fillna('S')

In [78]:
train['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [79]:
train['Embarked_num'] = LabelEncoder().fit_transform(train['Embarked'])

In [80]:
train['Embarked_num'].value_counts()

Embarked_num
2    646
0    168
1     77
Name: count, dtype: int64

Embarked는 탑승 항구의 이니셜을 나타냈습니다.

그런데, 우리는 이전에 배운 내용처럼 `LabelEncoder`를 통해서 수치형으로 변환해주었습니다.

하지만, 이대로 데이터를 기계학습을 시키면, 기계는 데이터 안에서 관계를 학습합니다.

즉, 'S' = 2, 'Q' = 1 이라고 되어 있는데, `Q` + `Q` = `S` 가 된다 라고 학습해버린다는 것이죠.

그렇기 때문에, 독립적인 데이터는 별도의 column으로 분리하고,
각각의 컬럼에 해당 값에만 **True** 나머지는 **False**를 갖습니다.
우리는 이것은 원 핫 인코딩 한다라고 합니다.

In [ ]:
train['Embarked'][:6]

0    S
1    C
2    S
3    S
4    S
5    Q
Name: Embarked, dtype: object

In [ ]:
train['Embarked_num'][:6]

0    2
1    0
2    2
3    2
4    2
5    1
Name: Embarked_num, dtype: int64

In [ ]:
# pandas 패키지 안에 one-hot encoding 타입으로 변경해주는 함수
pd.get_dummies(train['Embarked_num'][:6])

   0  1  2
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

In [ ]:
one_hot = pd.get_dummies(train['Embarked_num'][:6])

In [ ]:
one_hot.columns = ['C','Q','S']

In [ ]:
one_hot

   C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

위와 같이 column 을 분리시켜 **카테고리형 -> 수치형으로 변환**하면서 생기는 `수치형 값`의 관계를 끊어주어서 독립적인 형태로 바꾸어 줍니다.

**원핫인코딩**은 카테고리 (계절, 항구, 성별, 종류, 한식/일식/중식...)의 특성을 가지는 column에 대해서 적용 합니다.

In [ ]:
import numpy as np
import pandas as pd

## 전처리: Normalize (정규화)

부동산 가격을 예측하기 위해 상관관계가 있는 특성들을 도출한다고 하면,
집의 평수, 아파트의 나이, 지하철 역과의 거리, 대형마트와의 거리 등이
관련이 있을 것입니다.

집의 평수는 10평부터 100평까지 다양할 것이고, 아파트의 나이는 1년에서 20년,
지하철 역과의 거리는 0.1km부터 1km, 대형마트와의 거리도 1km에서 20km까지 다양할 것입니다.
문제는 '평수', '년', 'km' 등 각 특성의 단위도 다르고, 값의 범위도 꽤 차이가 있다는 것입니다.
우선 단위가 다르면 직접적인 비교가 불가능합니다. 사람의 키와 사람의 몸무게를 직접적으로
비교할 수 없는 것처럼 말이죠.

따라서 특성들의 단위를 무시할 수 있도록, 또한 특성들의 값의 범위를 비슷하게 만들어줄 필요가 있습니다.
그것이 바로 정규화 또는 표준화가 해주는 일입니다. 정규화와 표준화가 해주는 것을 특성 스케일링(feature scaling)
또는 데이터 스케일링(data scaling)이라고 부릅니다.

참고 사이트 : https://bskyvision.com/849

column 간에 다른 **min**, **max** 값을 가지는 경우, 정규화를 통해 최소치/ 최대값의 척도를 맞추어 주는 것

* 네이버 영화평점 (0점 ~ 10점): [2, 4, 6, 8, 10]
* 넷플릭스 영화평점 (0점 ~ 5점): [1, 2, 3, 4, 5]

In [81]:
movie = {'naver': [2, 4, 6, 8, 10],
         'netflix': [1, 2, 3, 4, 5]
         }

In [82]:
movie = pd.DataFrame(data=movie)
movie

   naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

In [83]:
# scikit-learn에서 MinMaxScaler는 Normalize의 기능으로 사용된다.
from sklearn.preprocessing import MinMaxScaler

In [84]:
# default값이 0~1사이로 설정
# 만약 0(min)~5(max)사이로 설정하려면,
min_max_scaler = MinMaxScaler(feature_range=(0, 5))

In [85]:
min_max_movie = min_max_scaler.fit_transform(movie)

In [86]:
type(min_max_movie)

numpy.ndarray

In [87]:
pd.DataFrame(min_max_movie, columns=['naver', 'netflix'])

   naver  netflix
0   0.00     0.00
1   1.25     1.25
2   2.50     2.50
3   3.75     3.75
4   5.00     5.00

## 표준화 (Standard Scaling)

**평균이 0과 표준편차가 1**이 되도록 변환

In [91]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

샘플데이터를 생성합니다.

In [92]:
x = np.arange(10)

In [93]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# outlier 추가
# outlier가 들어가서 전체data의 왜곡을 줌
x[9] = 1000

In [95]:
x

array([   0,    1,    2,    3,    4,    5,    6,    7,    8, 1000])

In [96]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [97]:
# fit_transfom은 2차 방정식에 사용되므로 reshape 필수

scaled = standard_scaler.fit_transform(x.reshape(-1, 1))

In [98]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [99]:
scaled.mean(), scaled.std()

(4.4408920985006264e-17, 1.0)

In [100]:
# scaled.mean()의 출력값을 소수점 2번째 자리 반올림
round(scaled.mean(), 2), scaled.std()

(0.0, 1.0)

# 데이터 전처리 절차

In [ ]:
# 데이터 전처리시 가장 먼저 수행할 것은? 결측치 해결

# 1> fillna(스칼라값 채워주기
##      평균값 : fillna(df['age']).mean())
##      중앙값 : fillna(df['age']).median())
##      최빈값 : fillna(df['age']).mode())
##      특정값 : fillna(0)

# 2> sklearn SimpleImputer(strategy = 'mean')
# mean, median, most_frequency, constant(특정값)


# 3> lagel Encoder
# 'S', 'C', 'Q'  -> 0, 1, 2 숫자로 변환
#'male', 'female' -> 1, 0 숫자로 변환


# 4> one-hot encoding
# 숫자 -> one-hot-encoding
# 0 -> [1,0,0]
# 1 -> [0,1,0]
# 2 -> [0,0,1]


# 정규화
# Feature의 scale을 변환해준다.
# 0~1로 변환 (0~5, 0~10)
# sklearn에 MinMaxScaler() 함수사용


# 표준화 (데이터 노이즈에 강하다, outlier 있는 경우)
# 평균이 0, 표준편차가 1이 되도록 반환
# sklearn에 StandardScaler() 함수사용